
# task saved as a .properties
id=1121
title=lllll
text=llllll
tags-count=5
n-subtasks=5
subtask-1-title=llllef
subtask-1-text=llllef
subtask-2-title=llllef
subtask-2-text=llllef
subtask-3-title=llllef
subtask-3-text=llllef
